Fix string union type with + operator
roblox-ts/roblox-ts pull request #1101
Opened 2020-09-13 21:18 UTC by Dionysusnu

2020-09-13 22:44 UTC, osyrisrblx requested changes

2020-09-13 22:44 UTC, osyrisrblx commented on src/TSTransformer/util/createBinaryFromOperator.ts
> +import { isStringSimpleType, isStringType } from "TSTransformer/util/types";
```suggestion
import { isStringType } from "TSTransformer/util/types";
```

2020-09-13 22:44 UTC, osyrisrblx commented on src/TSTransformer/util/createBinaryFromOperator.ts
> +import { isStringSimpleType, isStringType } from "TSTransformer/util/types";
`isStringSimpleType` is no longer used in this file.

2020-09-13 22:47 UTC, osyrisrblx approved these changes

2020-09-13 22:52 UTC, merged

2020-09-14 02:16 UTC, JamieFristrom commented
Alacrity!