Fix `Array.push` inserting multiple values for different tables
roblox-ts/roblox-ts pull request #2597
Opened 2024-01-18 12:26 UTC by rimuy

The macro currently doesn't create a temporary variable for the target array, which clones the table expression for each insert call and returns the incorrect size of the changed array when it's captured.

This has been happening since the method rework in https://github.com/roblox-ts/roblox-ts/pull/1853.
```ts
print([1, 2, 3].push(4, 5, 6));
```

Current emit:
```lua
-- Compiled with roblox-ts v2.2.0
-- ▼ Array.push ▼
table.insert({ 1, 2, 3 }, 4)
table.insert({ 1, 2, 3 }, 5)
table.insert({ 1, 2, 3 }, 6)
-- ▲ Array.push ▲
print(#({ 1, 2, 3 }))
return nil
```

Expected:
```lua
-- Compiled with roblox-ts v2.2.0
local _exp = { 1, 2, 3 }
-- ▼ Array.push ▼
table.insert(_exp, 4)
table.insert(_exp, 5)
table.insert(_exp, 6)
-- ▲ Array.push ▲
print(#_exp)
return nil
```

2024-01-18 12:54 UTC, Dionysusnu commented
That's my bad in the original PR. I think I assumed that the macro call prereq code would cover it, since it uses `expressionMightMutate`. However, that (rightly) considers an array literal to not be mutated, so it's never pushed to a variable.

In this addition, I think we could check for `args.length > 1 || resultIsUsed`? That avoids un-optimising the case where the `expression` is only used once, and thus not at risk of duplication.

2024-01-19 12:37 UTC, rimuy commented on src/TSTransformer/macros/propertyCallMacros.ts
> +		if (args.length === 0) {
Should probably add the comment back but place it here instead.

2024-02-07 18:29 UTC, osyrisrblx requested changes
Please add unit testing 🙏

2024-02-07 19:13 UTC, osyrisrblx approved these changes

2024-02-07 21:52 UTC, merged