Decorator tests & fix property decorators
roblox-ts/roblox-ts pull request #2759
Opened 2024-08-04 23:00 UTC by cmumme

Fixes #2756 and adds tests for:
- Property decorators
- Class decorators
- Method decorators
- Parameter decorators

This regression was introduced by #2460 and resulting in an assertion in transformMemberDecorators called by transformPropertyDecorators:
```
    at assert (c:\Users\camre.VIRT-MACHINE\OneDrive\Documents\Shared\Projects\2024\Roblox\cmumme\IKEAv2\node_modules\roblox-ts\out\Shared\util\assert.js:7:15)
    at transformMemberDecorators (c:\Users\camre.VIRT-MACHINE\OneDrive\Documents\Shared\Projects\2024\Roblox\cmumme\IKEAv2\node_modules\roblox-ts\out\TSTransformer\nodes\class\transformDecorators.js:34:33)
    at transformPropertyDecorators (c:\Users\camre.VIRT-MACHINE\OneDrive\Documents\Shared\Projects\2024\Roblox\cmumme\IKEAv2\node_modules\roblox-ts\out\TSTransformer\nodes\class\transformDecorators.js:78:12)
    at transformDecorators (c:\Users\camre.VIRT-MACHINE\OneDrive\Documents\Shared\Projects\2024\Roblox\cmumme\IKEAv2\node_modules\roblox-ts\out\TSTransformer\nodes\class\transformDecorators.js:116:58)
    at transformClassLikeDeclaration (c:\Users\camre.VIRT-MACHINE\OneDrive\Documents\Shared\Projects\2024\Roblox\cmumme\IKEAv2\node_modules\roblox-ts\out\TSTransformer\nodes\class\transformClassLikeDeclaration.js:252:101)
    at transformClassDeclaration (c:\Users\camre.VIRT-MACHINE\OneDrive\Documents\Shared\Projects\2024\Roblox\cmumme\IKEAv2\node_modules\roblox-ts\out\TSTransformer\nodes\statements\transformClassDeclaration.js:6:78)
    at transformStatement (c:\Users\camre.VIRT-MACHINE\OneDrive\Documents\Shared\Projects\2024\Roblox\cmumme\IKEAv2\node_modules\roblox-ts\out\TSTransformer\nodes\statements\transformStatement.js:76:16)
    at c:\Users\camre.VIRT-MACHINE\OneDrive\Documents\Shared\Projects\2024\Roblox\cmumme\IKEAv2\node_modules\roblox-ts\out\TSTransformer\nodes\transformStatementList.js:27:123
    at c:\Users\camre.VIRT-MACHINE\OneDrive\Documents\Shared\Projects\2024\Roblox\cmumme\IKEAv2\node_modules\roblox-ts\out\TSTransformer\classes\TransformState.js:132:60
    at TransformState.capturePrereqs (c:\Users\camre.VIRT-MACHINE\OneDrive\Documents\Shared\Projects\2024\Roblox\cmumme\IKEAv2\node_modules\roblox-ts\out\TSTransformer\classes\TransformState.js:127:9)
```

2024-08-04 23:06 UTC, cmumme commented
Need to add tests for non-static property/method/parameter decorators. Working on that now!

2024-08-05 16:52 UTC, Dionysusnu requested changes
The changes in transformDecorators.ts are incorrect, commenting out these asserts means the key can become duplicated. Using `member.name.getText()` is incorrect for computed property keys. (In general, getText() is not useful for the compiler, except when debugging)

The change in transformPropertyDeclaration.ts is incorrect, `name` is not the key, but the item being indexed. We should pass the result of `transformPropertyName` instead.

The tests look okay, though it would be good to test computed keys as well.

2024-08-05 17:15 UTC, cmumme commented
Added computed key tests and used proper property name fetching in both files. Still have those asserts commented out though, as I'm getting test compile failures without them from that assert in transformMemberDecorators.

2024-08-06 17:04 UTC, Dionysusnu requested changes

2024-08-23 20:49 UTC, Dionysusnu commented on src/TSTransformer/nodes/class/transformPropertyDeclaration.ts
> +		}
Any kind of property index, eg `[Symbol.iterator]() {}`. For bonus points, one that generates a prereq would be good as an extra unit test too.

2024-09-02 17:38 UTC, cmumme commented
I'll modify this PR to only include tests following the merge of #2787.

2024-09-05 01:08 UTC, merged